### ISSUE TITLE
Crash when trying to run through pip install on MAC

### ISSUE THREAD

**Issue by nitishMehrotra** [src-d/tmsc#5]
Command Executed : tmsc https://github.com/square/okhttp
Error Thrown: AttributeError: 'Topics' object has no attribute 'get_dependency'

Screenshot: 
<img width="1438" alt="screen shot 2018-02-22 at 8 40 57 pm" src="https://user-images.githubusercontent.com/3133988/36546175-baf9df0e-1810-11e8-864f-3aa3a15f9fb5.png">

OS: Mac
Babel Server running through docker with all recommended drivers installed.

It would be great if someone could help me with the issue
Thanks!

**Comment by vmarkovtsev** [comment]
Thanks for reporting! Should be fixed now, feel free to reopen if there are other problems.

**Comment by nitishMehrotra** [comment]
Thanks for the fix! The issue still persists when we do a pip install of the package. Do you want me to report that as a separate fix?

**Comment by vmarkovtsev** [comment]
I have just published the new version of the package.
